pdf:
  input_dir: "pdfs"
  output_dir: "output"
  chunk_strategy: "paragraph"
  save_format: "json"
  default_prompt: "image_analysis"  # 对应prompts/image_analysis.txt


model:
  name: "qwen-vl-max-latest"  # 模型名称
  api_key: "DASHSCOPE_API_KEY"  # 请在此处填写存储API密钥的环境变量名称
  # 使用方法：
  # 1. 先在系统中设置环境变量(如: setx QWEN_API_KEY "your_api_key")
  # 2. 在此处填写环境变量名称(如: QWEN_API_KEY)
  # 3. 程序会自动从环境变量读取实际API密钥
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # API基础URL